### ISSUE TITLE
Remove filter from images

### ISSUE THREAD

**Issue by mariozeats** [mariozeats/mariozeats#8]
I tried looking for it and attempted to adjust the opacity under .links in:
 themes>hugo-future-imperfect>static>css>add-on.css

but could never update, so ctrl+z'ed .
may have broken something because I still don't understand develop :(

**Comment by s-okai** [comment]
Commit: 244ddc6c07eb56686ee92a74a58e195c09e51cd2

**Comment by s-okai** [comment]
Resolved by #15
